// CS2 Items Database - comprehensive list of items for autocomplete
// Categories: Knife, Gloves, Rifle, SMG, Pistol, Shotgun, Machine Gun, Container, Sticker, Agent, Patch, Collectible, Key, Pass, Graffiti, Music Kit, Tool
const CS2_ITEMS = [
    // ===== KNIVES =====
    // Bayonet
    { name: "★ Bayonet | Doppler", type: "Knife" },
    { name: "★ Bayonet | Gamma Doppler", type: "Knife" },
    { name: "★ Bayonet | Marble Fade", type: "Knife" },
    { name: "★ Bayonet | Fade", type: "Knife" },
    { name: "★ Bayonet | Tiger Tooth", type: "Knife" },
    { name: "★ Bayonet | Slaughter", type: "Knife" },
    { name: "★ Bayonet | Crimson Web", type: "Knife" },
    { name: "★ Bayonet | Case Hardened", type: "Knife" },
    { name: "★ Bayonet | Autotronic", type: "Knife" },
    { name: "★ Bayonet | Lore", type: "Knife" },
    { name: "★ Bayonet | Damascus Steel", type: "Knife" },
    { name: "★ Bayonet | Rust Coat", type: "Knife" },
    { name: "★ Bayonet | Ultraviolet", type: "Knife" },
    { name: "★ Bayonet | Night", type: "Knife" },
    { name: "★ Bayonet | Blue Steel", type: "Knife" },
    { name: "★ Bayonet | Vanilla", type: "Knife" },
    { name: "★ Bayonet | Freehand", type: "Knife" },
    { name: "★ Bayonet | Bright Water", type: "Knife" },
    { name: "★ Bayonet | Black Laminate", type: "Knife" },
    // Karambit
    { name: "★ Karambit | Doppler", type: "Knife" },
    { name: "★ Karambit | Gamma Doppler", type: "Knife" },
    { name: "★ Karambit | Marble Fade", type: "Knife" },
    { name: "★ Karambit | Fade", type: "Knife" },
    { name: "★ Karambit | Tiger Tooth", type: "Knife" },
    { name: "★ Karambit | Slaughter", type: "Knife" },
    { name: "★ Karambit | Crimson Web", type: "Knife" },
    { name: "★ Karambit | Case Hardened", type: "Knife" },
    { name: "★ Karambit | Autotronic", type: "Knife" },
    { name: "★ Karambit | Lore", type: "Knife" },
    { name: "★ Karambit | Damascus Steel", type: "Knife" },
    { name: "★ Karambit | Rust Coat", type: "Knife" },
    { name: "★ Karambit | Ultraviolet", type: "Knife" },
    { name: "★ Karambit | Night", type: "Knife" },
    { name: "★ Karambit | Blue Steel", type: "Knife" },
    { name: "★ Karambit | Vanilla", type: "Knife" },
    { name: "★ Karambit | Black Laminate", type: "Knife" },
    { name: "★ Karambit | Bright Water", type: "Knife" },
    // M9 Bayonet
    { name: "★ M9 Bayonet | Doppler", type: "Knife" },
    { name: "★ M9 Bayonet | Gamma Doppler", type: "Knife" },
    { name: "★ M9 Bayonet | Marble Fade", type: "Knife" },
    { name: "★ M9 Bayonet | Fade", type: "Knife" },
    { name: "★ M9 Bayonet | Tiger Tooth", type: "Knife" },
    { name: "★ M9 Bayonet | Slaughter", type: "Knife" },
    { name: "★ M9 Bayonet | Crimson Web", type: "Knife" },
    { name: "★ M9 Bayonet | Case Hardened", type: "Knife" },
    { name: "★ M9 Bayonet | Autotronic", type: "Knife" },
    { name: "★ M9 Bayonet | Lore", type: "Knife" },
    { name: "★ M9 Bayonet | Damascus Steel", type: "Knife" },
    { name: "★ M9 Bayonet | Rust Coat", type: "Knife" },
    { name: "★ M9 Bayonet | Ultraviolet", type: "Knife" },
    { name: "★ M9 Bayonet | Night", type: "Knife" },
    { name: "★ M9 Bayonet | Blue Steel", type: "Knife" },
    { name: "★ M9 Bayonet | Vanilla", type: "Knife" },
    { name: "★ M9 Bayonet | Black Laminate", type: "Knife" },
    // Butterfly Knife
    { name: "★ Butterfly Knife | Doppler", type: "Knife" },
    { name: "★ Butterfly Knife | Gamma Doppler", type: "Knife" },
    { name: "★ Butterfly Knife | Marble Fade", type: "Knife" },
    { name: "★ Butterfly Knife | Fade", type: "Knife" },
    { name: "★ Butterfly Knife | Tiger Tooth", type: "Knife" },
    { name: "★ Butterfly Knife | Slaughter", type: "Knife" },
    { name: "★ Butterfly Knife | Crimson Web", type: "Knife" },
    { name: "★ Butterfly Knife | Case Hardened", type: "Knife" },
    { name: "★ Butterfly Knife | Autotronic", type: "Knife" },
    { name: "★ Butterfly Knife | Lore", type: "Knife" },
    { name: "★ Butterfly Knife | Damascus Steel", type: "Knife" },
    { name: "★ Butterfly Knife | Rust Coat", type: "Knife" },
    { name: "★ Butterfly Knife | Ultraviolet", type: "Knife" },
    { name: "★ Butterfly Knife | Night", type: "Knife" },
    { name: "★ Butterfly Knife | Blue Steel", type: "Knife" },
    { name: "★ Butterfly Knife | Vanilla", type: "Knife" },
    { name: "★ Butterfly Knife | Black Laminate", type: "Knife" },
    // Flip Knife
    { name: "★ Flip Knife | Doppler", type: "Knife" },
    { name: "★ Flip Knife | Gamma Doppler", type: "Knife" },
    { name: "★ Flip Knife | Marble Fade", type: "Knife" },
    { name: "★ Flip Knife | Fade", type: "Knife" },
    { name: "★ Flip Knife | Tiger Tooth", type: "Knife" },
    { name: "★ Flip Knife | Slaughter", type: "Knife" },
    { name: "★ Flip Knife | Crimson Web", type: "Knife" },
    { name: "★ Flip Knife | Case Hardened", type: "Knife" },
    { name: "★ Flip Knife | Autotronic", type: "Knife" },
    { name: "★ Flip Knife | Lore", type: "Knife" },
    { name: "★ Flip Knife | Vanilla", type: "Knife" },
    { name: "★ Flip Knife | Rust Coat", type: "Knife" },
    { name: "★ Flip Knife | Ultraviolet", type: "Knife" },
    { name: "★ Flip Knife | Damascus Steel", type: "Knife" },
    // Gut Knife
    { name: "★ Gut Knife | Doppler", type: "Knife" },
    { name: "★ Gut Knife | Gamma Doppler", type: "Knife" },
    { name: "★ Gut Knife | Marble Fade", type: "Knife" },
    { name: "★ Gut Knife | Fade", type: "Knife" },
    { name: "★ Gut Knife | Tiger Tooth", type: "Knife" },
    { name: "★ Gut Knife | Slaughter", type: "Knife" },
    { name: "★ Gut Knife | Crimson Web", type: "Knife" },
    { name: "★ Gut Knife | Case Hardened", type: "Knife" },
    { name: "★ Gut Knife | Autotronic", type: "Knife" },
    { name: "★ Gut Knife | Lore", type: "Knife" },
    { name: "★ Gut Knife | Vanilla", type: "Knife" },
    // Huntsman Knife
    { name: "★ Huntsman Knife | Doppler", type: "Knife" },
    { name: "★ Huntsman Knife | Fade", type: "Knife" },
    { name: "★ Huntsman Knife | Slaughter", type: "Knife" },
    { name: "★ Huntsman Knife | Crimson Web", type: "Knife" },
    { name: "★ Huntsman Knife | Case Hardened", type: "Knife" },
    { name: "★ Huntsman Knife | Vanilla", type: "Knife" },
    // Falchion Knife
    { name: "★ Falchion Knife | Doppler", type: "Knife" },
    { name: "★ Falchion Knife | Fade", type: "Knife" },
    { name: "★ Falchion Knife | Slaughter", type: "Knife" },
    { name: "★ Falchion Knife | Crimson Web", type: "Knife" },
    { name: "★ Falchion Knife | Case Hardened", type: "Knife" },
    { name: "★ Falchion Knife | Vanilla", type: "Knife" },
    // Shadow Daggers
    { name: "★ Shadow Daggers | Doppler", type: "Knife" },
    { name: "★ Shadow Daggers | Fade", type: "Knife" },
    { name: "★ Shadow Daggers | Slaughter", type: "Knife" },
    { name: "★ Shadow Daggers | Crimson Web", type: "Knife" },
    { name: "★ Shadow Daggers | Vanilla", type: "Knife" },
    // Bowie Knife
    { name: "★ Bowie Knife | Doppler", type: "Knife" },
    { name: "★ Bowie Knife | Fade", type: "Knife" },
    { name: "★ Bowie Knife | Slaughter", type: "Knife" },
    { name: "★ Bowie Knife | Crimson Web", type: "Knife" },
    { name: "★ Bowie Knife | Vanilla", type: "Knife" },
    // Talon Knife
    { name: "★ Talon Knife | Doppler", type: "Knife" },
    { name: "★ Talon Knife | Marble Fade", type: "Knife" },
    { name: "★ Talon Knife | Fade", type: "Knife" },
    { name: "★ Talon Knife | Tiger Tooth", type: "Knife" },
    { name: "★ Talon Knife | Slaughter", type: "Knife" },
    { name: "★ Talon Knife | Crimson Web", type: "Knife" },
    { name: "★ Talon Knife | Case Hardened", type: "Knife" },
    { name: "★ Talon Knife | Vanilla", type: "Knife" },
    // Stiletto Knife
    { name: "★ Stiletto Knife | Doppler", type: "Knife" },
    { name: "★ Stiletto Knife | Fade", type: "Knife" },
    { name: "★ Stiletto Knife | Slaughter", type: "Knife" },
    { name: "★ Stiletto Knife | Crimson Web", type: "Knife" },
    { name: "★ Stiletto Knife | Vanilla", type: "Knife" },
    // Ursus Knife
    { name: "★ Ursus Knife | Doppler", type: "Knife" },
    { name: "★ Ursus Knife | Fade", type: "Knife" },
    { name: "★ Ursus Knife | Slaughter", type: "Knife" },
    { name: "★ Ursus Knife | Crimson Web", type: "Knife" },
    { name: "★ Ursus Knife | Vanilla", type: "Knife" },
    // Navaja Knife
    { name: "★ Navaja Knife | Doppler", type: "Knife" },
    { name: "★ Navaja Knife | Fade", type: "Knife" },
    { name: "★ Navaja Knife | Slaughter", type: "Knife" },
    { name: "★ Navaja Knife | Crimson Web", type: "Knife" },
    { name: "★ Navaja Knife | Vanilla", type: "Knife" },
    // Paracord Knife
    { name: "★ Paracord Knife | Slaughter", type: "Knife" },
    { name: "★ Paracord Knife | Crimson Web", type: "Knife" },
    { name: "★ Paracord Knife | Case Hardened", type: "Knife" },
    { name: "★ Paracord Knife | Fade", type: "Knife" },
    // Survival Knife
    { name: "★ Survival Knife | Slaughter", type: "Knife" },
    { name: "★ Survival Knife | Crimson Web", type: "Knife" },
    { name: "★ Survival Knife | Case Hardened", type: "Knife" },
    { name: "★ Survival Knife | Fade", type: "Knife" },
    // Nomad Knife
    { name: "★ Nomad Knife | Slaughter", type: "Knife" },
    { name: "★ Nomad Knife | Crimson Web", type: "Knife" },
    { name: "★ Nomad Knife | Fade", type: "Knife" },
    // Skeleton Knife
    { name: "★ Skeleton Knife | Slaughter", type: "Knife" },
    { name: "★ Skeleton Knife | Crimson Web", type: "Knife" },
    { name: "★ Skeleton Knife | Fade", type: "Knife" },
    { name: "★ Skeleton Knife | Case Hardened", type: "Knife" },
    { name: "★ Skeleton Knife | Vanilla", type: "Knife" },
    // Classic Knife
    { name: "★ Classic Knife | Fade", type: "Knife" },
    { name: "★ Classic Knife | Crimson Web", type: "Knife" },
    { name: "★ Classic Knife | Slaughter", type: "Knife" },
    { name: "★ Classic Knife | Case Hardened", type: "Knife" },
    { name: "★ Classic Knife | Vanilla", type: "Knife" },
    // Kukri Knife
    { name: "★ Kukri Knife | Doppler", type: "Knife" },
    { name: "★ Kukri Knife | Gamma Doppler", type: "Knife" },
    { name: "★ Kukri Knife | Marble Fade", type: "Knife" },
    { name: "★ Kukri Knife | Fade", type: "Knife" },
    { name: "★ Kukri Knife | Tiger Tooth", type: "Knife" },
    { name: "★ Kukri Knife | Slaughter", type: "Knife" },
    { name: "★ Kukri Knife | Crimson Web", type: "Knife" },
    { name: "★ Kukri Knife | Case Hardened", type: "Knife" },
    { name: "★ Kukri Knife | Autotronic", type: "Knife" },
    { name: "★ Kukri Knife | Lore", type: "Knife" },
    { name: "★ Kukri Knife | Vanilla", type: "Knife" },

    // ===== GLOVES =====
    { name: "★ Sport Gloves | Pandora's Box", type: "Gloves" },
    { name: "★ Sport Gloves | Hedge Maze", type: "Gloves" },
    { name: "★ Sport Gloves | Superconductor", type: "Gloves" },
    { name: "★ Sport Gloves | Arid", type: "Gloves" },
    { name: "★ Sport Gloves | Vice", type: "Gloves" },
    { name: "★ Sport Gloves | Omega", type: "Gloves" },
    { name: "★ Sport Gloves | Amphibious", type: "Gloves" },
    { name: "★ Sport Gloves | Bronze Morph", type: "Gloves" },
    { name: "★ Sport Gloves | Nocts", type: "Gloves" },
    { name: "★ Sport Gloves | Scarlet Shamagh", type: "Gloves" },
    { name: "★ Driver Gloves | King Snake", type: "Gloves" },
    { name: "★ Driver Gloves | Crimson Weave", type: "Gloves" },
    { name: "★ Driver Gloves | Imperial Plaid", type: "Gloves" },
    { name: "★ Driver Gloves | Lunar Weave", type: "Gloves" },
    { name: "★ Driver Gloves | Diamondback", type: "Gloves" },
    { name: "★ Driver Gloves | Overtake", type: "Gloves" },
    { name: "★ Driver Gloves | Queen Jaguar", type: "Gloves" },
    { name: "★ Driver Gloves | Snow Leopard", type: "Gloves" },
    { name: "★ Driver Gloves | Black Tie", type: "Gloves" },
    { name: "★ Hand Wraps | Cobalt Skulls", type: "Gloves" },
    { name: "★ Hand Wraps | Slaughter", type: "Gloves" },
    { name: "★ Hand Wraps | Leather", type: "Gloves" },
    { name: "★ Hand Wraps | Spruce DDPAT", type: "Gloves" },
    { name: "★ Hand Wraps | Badlands", type: "Gloves" },
    { name: "★ Hand Wraps | Duct Tape", type: "Gloves" },
    { name: "★ Hand Wraps | Overprint", type: "Gloves" },
    { name: "★ Hand Wraps | Arboreal", type: "Gloves" },
    { name: "★ Hand Wraps | Giraffe", type: "Gloves" },
    { name: "★ Hand Wraps | CAUTION!", type: "Gloves" },
    { name: "★ Moto Gloves | Spearmint", type: "Gloves" },
    { name: "★ Moto Gloves | Cool Mint", type: "Gloves" },
    { name: "★ Moto Gloves | Eclipse", type: "Gloves" },
    { name: "★ Moto Gloves | Transport", type: "Gloves" },
    { name: "★ Moto Gloves | Boom!", type: "Gloves" },
    { name: "★ Moto Gloves | Polygon", type: "Gloves" },
    { name: "★ Moto Gloves | Blood Pressure", type: "Gloves" },
    { name: "★ Moto Gloves | Smoke Out", type: "Gloves" },
    { name: "★ Moto Gloves | 3rd Commando Company", type: "Gloves" },
    { name: "★ Specialist Gloves | Crimson Kimono", type: "Gloves" },
    { name: "★ Specialist Gloves | Emerald Web", type: "Gloves" },
    { name: "★ Specialist Gloves | Fade", type: "Gloves" },
    { name: "★ Specialist Gloves | Forest DDPAT", type: "Gloves" },
    { name: "★ Specialist Gloves | Foundation", type: "Gloves" },
    { name: "★ Specialist Gloves | Mogul", type: "Gloves" },
    { name: "★ Specialist Gloves | Marble Fade", type: "Gloves" },
    { name: "★ Specialist Gloves | Tiger Strike", type: "Gloves" },
    { name: "★ Specialist Gloves | Buckshot", type: "Gloves" },
    { name: "★ Specialist Gloves | Field Agent", type: "Gloves" },
    { name: "★ Hydra Gloves | Emerald", type: "Gloves" },
    { name: "★ Hydra Gloves | Case Hardened", type: "Gloves" },
    { name: "★ Hydra Gloves | Rattler", type: "Gloves" },
    { name: "★ Hydra Gloves | Mangrove", type: "Gloves" },
    { name: "★ Broken Fang Gloves | Yellow-banded", type: "Gloves" },
    { name: "★ Broken Fang Gloves | Jade", type: "Gloves" },
    { name: "★ Broken Fang Gloves | Needle Point", type: "Gloves" },
    { name: "★ Broken Fang Gloves | Unhinged", type: "Gloves" },

    // ===== AK-47 =====
    { name: "AK-47 | Wild Lotus", type: "Rifle" },
    { name: "AK-47 | Fire Serpent", type: "Rifle" },
    { name: "AK-47 | Hydroponic", type: "Rifle" },
    { name: "AK-47 | Fuel Injector", type: "Rifle" },
    { name: "AK-47 | Bloodsport", type: "Rifle" },
    { name: "AK-47 | Vulcan", type: "Rifle" },
    { name: "AK-47 | The Empress", type: "Rifle" },
    { name: "AK-47 | Neon Rider", type: "Rifle" },
    { name: "AK-47 | Neon Revolution", type: "Rifle" },
    { name: "AK-47 | Asiimov", type: "Rifle" },
    { name: "AK-47 | Phantom Disruptor", type: "Rifle" },
    { name: "AK-47 | Nightwish", type: "Rifle" },
    { name: "AK-47 | Ice Coaled", type: "Rifle" },
    { name: "AK-47 | Gold Arabesque", type: "Rifle" },
    { name: "AK-47 | Wasteland Rebel", type: "Rifle" },
    { name: "AK-47 | Frontside Misty", type: "Rifle" },
    { name: "AK-47 | Jaguar", type: "Rifle" },
    { name: "AK-47 | Point Disarray", type: "Rifle" },
    { name: "AK-47 | Redline", type: "Rifle" },
    { name: "AK-47 | Blue Laminate", type: "Rifle" },
    { name: "AK-47 | Red Laminate", type: "Rifle" },
    { name: "AK-47 | Case Hardened", type: "Rifle" },
    { name: "AK-47 | Slate", type: "Rifle" },
    { name: "AK-47 | Inheritance", type: "Rifle" },
    { name: "AK-47 | Head Shot", type: "Rifle" },
    { name: "AK-47 | Legion of Anubis", type: "Rifle" },
    { name: "AK-47 | Rat Rod", type: "Rifle" },
    { name: "AK-47 | Safari Mesh", type: "Rifle" },
    { name: "AK-47 | Elite Build", type: "Rifle" },
    { name: "AK-47 | Orbit Mk01", type: "Rifle" },
    { name: "AK-47 | Leet Museo", type: "Rifle" },

    // ===== AWP =====
    { name: "AWP | Dragon Lore", type: "Rifle" },
    { name: "AWP | Gungnir", type: "Rifle" },
    { name: "AWP | The Prince", type: "Rifle" },
    { name: "AWP | Medusa", type: "Rifle" },
    { name: "AWP | Fade", type: "Rifle" },
    { name: "AWP | Lightning Strike", type: "Rifle" },
    { name: "AWP | Asiimov", type: "Rifle" },
    { name: "AWP | Hyper Beast", type: "Rifle" },
    { name: "AWP | Neo-Noir", type: "Rifle" },
    { name: "AWP | Wildfire", type: "Rifle" },
    { name: "AWP | Containment Breach", type: "Rifle" },
    { name: "AWP | Printstream", type: "Rifle" },
    { name: "AWP | Chromatic Aberration", type: "Rifle" },
    { name: "AWP | Fever Dream", type: "Rifle" },
    { name: "AWP | Electric Hive", type: "Rifle" },
    { name: "AWP | Redline", type: "Rifle" },
    { name: "AWP | Boom", type: "Rifle" },
    { name: "AWP | Man-o'-war", type: "Rifle" },
    { name: "AWP | Oni Taiji", type: "Rifle" },
    { name: "AWP | PAW", type: "Rifle" },
    { name: "AWP | Corticera", type: "Rifle" },
    { name: "AWP | Atheris", type: "Rifle" },
    { name: "AWP | Silk Tiger", type: "Rifle" },
    { name: "AWP | Duality", type: "Rifle" },
    { name: "AWP | Exoskeleton", type: "Rifle" },
    { name: "AWP | Desert Hydra", type: "Rifle" },

    // ===== M4A4 =====
    { name: "M4A4 | Howl", type: "Rifle" },
    { name: "M4A4 | Poseidon", type: "Rifle" },
    { name: "M4A4 | The Emperor", type: "Rifle" },
    { name: "M4A4 | Asiimov", type: "Rifle" },
    { name: "M4A4 | Neo-Noir", type: "Rifle" },
    { name: "M4A4 | Desolate Space", type: "Rifle" },
    { name: "M4A4 | Buzz Kill", type: "Rifle" },
    { name: "M4A4 | In Living Color", type: "Rifle" },
    { name: "M4A4 | Royal Paladin", type: "Rifle" },
    { name: "M4A4 | Tooth Fairy", type: "Rifle" },
    { name: "M4A4 | Spider Lily", type: "Rifle" },
    { name: "M4A4 | Temukau", type: "Rifle" },
    { name: "M4A4 | Cyber Security", type: "Rifle" },
    { name: "M4A4 | Hellfire", type: "Rifle" },
    { name: "M4A4 | Dragon King", type: "Rifle" },
    { name: "M4A4 | X-Ray", type: "Rifle" },
    { name: "M4A4 | Zirka", type: "Rifle" },
    { name: "M4A4 | Daybreak", type: "Rifle" },
    { name: "M4A4 | Printstream", type: "Rifle" },

    // ===== M4A1-S =====
    { name: "M4A1-S | Welcome to the Jungle", type: "Rifle" },
    { name: "M4A1-S | Knight", type: "Rifle" },
    { name: "M4A1-S | Hot Rod", type: "Rifle" },
    { name: "M4A1-S | Chantico's Fire", type: "Rifle" },
    { name: "M4A1-S | Golden Coil", type: "Rifle" },
    { name: "M4A1-S | Hyper Beast", type: "Rifle" },
    { name: "M4A1-S | Mecha Industries", type: "Rifle" },
    { name: "M4A1-S | Printstream", type: "Rifle" },
    { name: "M4A1-S | Decimator", type: "Rifle" },
    { name: "M4A1-S | Player Two", type: "Rifle" },
    { name: "M4A1-S | Imminent Danger", type: "Rifle" },
    { name: "M4A1-S | Cyrex", type: "Rifle" },
    { name: "M4A1-S | Nightmare", type: "Rifle" },
    { name: "M4A1-S | Atomic Alloy", type: "Rifle" },
    { name: "M4A1-S | Leaded Glass", type: "Rifle" },
    { name: "M4A1-S | Blue Phosphor", type: "Rifle" },
    { name: "M4A1-S | Emphorosaur-S", type: "Rifle" },
    { name: "M4A1-S | Night Terror", type: "Rifle" },

    // ===== Desert Eagle =====
    { name: "Desert Eagle | Blaze", type: "Pistol" },
    { name: "Desert Eagle | Hand Cannon", type: "Pistol" },
    { name: "Desert Eagle | Kumicho Dragon", type: "Pistol" },
    { name: "Desert Eagle | Mecha Industries", type: "Pistol" },
    { name: "Desert Eagle | Code Red", type: "Pistol" },
    { name: "Desert Eagle | Printstream", type: "Pistol" },
    { name: "Desert Eagle | Ocean Drive", type: "Pistol" },
    { name: "Desert Eagle | Trigger Discipline", type: "Pistol" },
    { name: "Desert Eagle | Golden Koi", type: "Pistol" },
    { name: "Desert Eagle | Hypnotic", type: "Pistol" },
    { name: "Desert Eagle | Conspiracy", type: "Pistol" },
    { name: "Desert Eagle | Fennec Fox", type: "Pistol" },
    { name: "Desert Eagle | Heat Treated", type: "Pistol" },

    // ===== USP-S =====
    { name: "USP-S | Kill Confirmed", type: "Pistol" },
    { name: "USP-S | Neo-Noir", type: "Pistol" },
    { name: "USP-S | Printstream", type: "Pistol" },
    { name: "USP-S | Caiman", type: "Pistol" },
    { name: "USP-S | Cortex", type: "Pistol" },
    { name: "USP-S | Orion", type: "Pistol" },
    { name: "USP-S | Overgrowth", type: "Pistol" },
    { name: "USP-S | Monster Mashup", type: "Pistol" },
    { name: "USP-S | Road Rash", type: "Pistol" },
    { name: "USP-S | Guardian", type: "Pistol" },
    { name: "USP-S | The Traitor", type: "Pistol" },
    { name: "USP-S | Ticket to Hell", type: "Pistol" },
    { name: "USP-S | Whiteout", type: "Pistol" },

    // ===== Glock-18 =====
    { name: "Glock-18 | Fade", type: "Pistol" },
    { name: "Glock-18 | Gamma Doppler", type: "Pistol" },
    { name: "Glock-18 | Wasteland Rebel", type: "Pistol" },
    { name: "Glock-18 | Water Elemental", type: "Pistol" },
    { name: "Glock-18 | Bullet Queen", type: "Pistol" },
    { name: "Glock-18 | Vogue", type: "Pistol" },
    { name: "Glock-18 | Neo-Noir", type: "Pistol" },
    { name: "Glock-18 | Synth Leaf", type: "Pistol" },
    { name: "Glock-18 | Twilight Galaxy", type: "Pistol" },
    { name: "Glock-18 | Reactor", type: "Pistol" },
    { name: "Glock-18 | Royal Legion", type: "Pistol" },
    { name: "Glock-18 | Weasel", type: "Pistol" },

    // ===== Other Pistols =====
    { name: "Five-SeveN | Monkey Business", type: "Pistol" },
    { name: "Five-SeveN | Hyper Beast", type: "Pistol" },
    { name: "Five-SeveN | Angry Mob", type: "Pistol" },
    { name: "Five-SeveN | Case Hardened", type: "Pistol" },
    { name: "P250 | See Ya Later", type: "Pistol" },
    { name: "P250 | Asiimov", type: "Pistol" },
    { name: "P250 | Nuclear Threat", type: "Pistol" },
    { name: "CZ75-Auto | Victoria", type: "Pistol" },
    { name: "CZ75-Auto | Xiangliu", type: "Pistol" },
    { name: "Tec-9 | Fuel Injector", type: "Pistol" },
    { name: "Tec-9 | Decimator", type: "Pistol" },
    { name: "R8 Revolver | Fade", type: "Pistol" },
    { name: "R8 Revolver | Amber Fade", type: "Pistol" },
    { name: "P2000 | Fire Elemental", type: "Pistol" },
    { name: "P2000 | Ocean Foam", type: "Pistol" },
    { name: "Dual Berettas | Cobalt Quartz", type: "Pistol" },
    { name: "Dual Berettas | Melondrama", type: "Pistol" },

    // ===== Other Rifles =====
    { name: "SG 553 | Integrale", type: "Rifle" },
    { name: "SG 553 | Cyrex", type: "Rifle" },
    { name: "AUG | Akihabara Accept", type: "Rifle" },
    { name: "AUG | Hot Rod", type: "Rifle" },
    { name: "AUG | Chameleon", type: "Rifle" },
    { name: "AUG | Flame Jörmungandr", type: "Rifle" },
    { name: "SSG 08 | Dragonfire", type: "Rifle" },
    { name: "SSG 08 | Blood in the Water", type: "Rifle" },
    { name: "SSG 08 | Turbo Peek", type: "Rifle" },
    { name: "SCAR-20 | Emerald", type: "Rifle" },
    { name: "G3SG1 | The Executioner", type: "Rifle" },
    { name: "FAMAS | Commemoration", type: "Rifle" },
    { name: "FAMAS | Roll Cage", type: "Rifle" },
    { name: "Galil AR | Chatterbox", type: "Rifle" },
    { name: "Galil AR | Cerberus", type: "Rifle" },

    // ===== SMGs =====
    { name: "MP9 | Wild Lily", type: "SMG" },
    { name: "MP9 | Hydra", type: "SMG" },
    { name: "MP9 | Rose Iron", type: "SMG" },
    { name: "MP7 | Nemesis", type: "SMG" },
    { name: "MP7 | Bloodsport", type: "SMG" },
    { name: "UMP-45 | Primal Saber", type: "SMG" },
    { name: "UMP-45 | Crime Scene", type: "SMG" },
    { name: "P90 | Asiimov", type: "SMG" },
    { name: "P90 | Death by Kitty", type: "SMG" },
    { name: "P90 | Emerald Dragon", type: "SMG" },
    { name: "MAC-10 | Neon Rider", type: "SMG" },
    { name: "MAC-10 | Case Hardened", type: "SMG" },
    { name: "PP-Bizon | Judgement of Anubis", type: "SMG" },

    // ===== Shotguns & Machine Guns =====
    { name: "MAG-7 | Justice", type: "Shotgun" },
    { name: "XM1014 | Incinegator", type: "Shotgun" },
    { name: "Nova | Hyper Beast", type: "Shotgun" },
    { name: "Sawed-Off | The Kraken", type: "Shotgun" },
    { name: "M249 | Magma", type: "Machine Gun" },
    { name: "Negev | Mjölnir", type: "Machine Gun" },

    // ===== CASES =====
    { name: "Revolution Case", type: "Container" },
    { name: "Recoil Case", type: "Container" },
    { name: "Dreams & Nightmares Case", type: "Container" },
    { name: "Fracture Case", type: "Container" },
    { name: "Snakebite Case", type: "Container" },
    { name: "Operation Broken Fang Case", type: "Container" },
    { name: "Clutch Case", type: "Container" },
    { name: "Prisma Case", type: "Container" },
    { name: "Prisma 2 Case", type: "Container" },
    { name: "CS20 Case", type: "Container" },
    { name: "Danger Zone Case", type: "Container" },
    { name: "Horizon Case", type: "Container" },
    { name: "Spectrum Case", type: "Container" },
    { name: "Spectrum 2 Case", type: "Container" },
    { name: "Glove Case", type: "Container" },
    { name: "Gamma Case", type: "Container" },
    { name: "Gamma 2 Case", type: "Container" },
    { name: "Chroma Case", type: "Container" },
    { name: "Chroma 2 Case", type: "Container" },
    { name: "Chroma 3 Case", type: "Container" },
    { name: "Shadow Case", type: "Container" },
    { name: "Falchion Case", type: "Container" },
    { name: "Revolver Case", type: "Container" },
    { name: "Wildfire Case", type: "Container" },
    { name: "Huntsman Weapon Case", type: "Container" },
    { name: "Operation Phoenix Weapon Case", type: "Container" },
    { name: "Operation Breakout Weapon Case", type: "Container" },
    { name: "Operation Vanguard Weapon Case", type: "Container" },
    { name: "Operation Hydra Case", type: "Container" },
    { name: "Operation Bravo Case", type: "Container" },
    { name: "CS:GO Weapon Case", type: "Container" },
    { name: "CS:GO Weapon Case 2", type: "Container" },
    { name: "CS:GO Weapon Case 3", type: "Container" },
    { name: "eSports 2013 Case", type: "Container" },
    { name: "eSports 2013 Winter Case", type: "Container" },
    { name: "eSports 2014 Summer Case", type: "Container" },
    { name: "Winter Offensive Weapon Case", type: "Container" },
    { name: "Kilowatt Case", type: "Container" },
    { name: "Gallery Case", type: "Container" },

    // ===== STICKERS (popular investment ones) =====
    { name: "Sticker | Katowice 2014 (Foil)", type: "Sticker" },
    { name: "Sticker | iBUYPOWER | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Titan | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Reason Gaming | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Natus Vincere | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Team LDLC.com | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Vox Eminor | Katowice 2014", type: "Sticker" },
    { name: "Sticker | compLexity Gaming | Katowice 2014", type: "Sticker" },
    { name: "Sticker | HellRaisers | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Team Dignitas | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Clan-Mystik | Katowice 2014", type: "Sticker" },
    { name: "Sticker | mousesports | Katowice 2014", type: "Sticker" },
    { name: "Sticker | 3DMAX | Katowice 2014", type: "Sticker" },
    { name: "Sticker | LGB eSports | Katowice 2014", type: "Sticker" },
    { name: "Sticker | iBUYPOWER (Holo) | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Titan (Holo) | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Natus Vincere (Holo) | Katowice 2014", type: "Sticker" },
    { name: "Sticker | Crown (Foil)", type: "Sticker" },
    { name: "Sticker | Howling Dawn", type: "Sticker" },
    { name: "Sticker | Flammable (Foil)", type: "Sticker" },
    { name: "Sticker | Headhunter (Foil)", type: "Sticker" },
    { name: "Sticker | Katowice 2015 (Foil)", type: "Sticker" },
    { name: "Sticker | Cologne 2014 (Foil)", type: "Sticker" },

    // ===== CAPSULES =====
    { name: "Katowice 2014 Legends (Holo/Foil)", type: "Container" },
    { name: "Katowice 2014 Challengers (Holo/Foil)", type: "Container" },
    { name: "Katowice 2015 Legends (Holo/Foil)", type: "Container" },
    { name: "Katowice 2015 Challengers (Holo/Foil)", type: "Container" },
    { name: "Cologne 2014 Legends (Holo/Foil)", type: "Container" },
    { name: "Paris 2023 Legends Sticker Capsule", type: "Container" },
    { name: "Paris 2023 Challengers Sticker Capsule", type: "Container" },
    { name: "Paris 2023 Contenders Sticker Capsule", type: "Container" },
    { name: "Copenhagen 2024 Legends Sticker Capsule", type: "Container" },
    { name: "Copenhagen 2024 Challengers Sticker Capsule", type: "Container" },
    { name: "Copenhagen 2024 Contenders Sticker Capsule", type: "Container" },
    { name: "Shanghai 2024 Legends Sticker Capsule", type: "Container" },
    { name: "Shanghai 2024 Challengers Sticker Capsule", type: "Container" },
    { name: "Shanghai 2024 Contenders Sticker Capsule", type: "Container" },
    { name: "Austin 2025 Legends Sticker Capsule", type: "Container" },
    { name: "Austin 2025 Challengers Sticker Capsule", type: "Container" },
    { name: "Austin 2025 Contenders Sticker Capsule", type: "Container" },
    { name: "Antwerp 2022 Legends Sticker Capsule", type: "Container" },
    { name: "Antwerp 2022 Challengers Sticker Capsule", type: "Container" },
    { name: "Antwerp 2022 Contenders Sticker Capsule", type: "Container" },
    { name: "Rio 2022 Legends Sticker Capsule", type: "Container" },
    { name: "Rio 2022 Challengers Sticker Capsule", type: "Container" },
    { name: "Rio 2022 Contenders Sticker Capsule", type: "Container" },
    { name: "Stockholm 2021 Legends Sticker Capsule", type: "Container" },
    { name: "Stockholm 2021 Challengers Sticker Capsule", type: "Container" },
    { name: "Stockholm 2021 Contenders Sticker Capsule", type: "Container" },
    { name: "RMR 2020 Legends", type: "Container" },
    { name: "RMR 2020 Challengers", type: "Container" },
    { name: "RMR 2020 Contenders", type: "Container" },
    { name: "Berlin 2019 Legends (Holo/Foil)", type: "Container" },
    { name: "Berlin 2019 Minor Challengers (Holo/Foil)", type: "Container" },
    { name: "Katowice 2019 Legends (Holo/Foil)", type: "Container" },
    { name: "Katowice 2019 Minor Challengers (Holo/Foil)", type: "Container" },
    { name: "Community Sticker Capsule 1", type: "Container" },
    { name: "Sticker Capsule", type: "Container" },
    { name: "Sticker Capsule 2", type: "Container" },

    // ===== AGENTS =====
    { name: "Master Agent | FBI", type: "Agent" },
    { name: "Operator | FBI SWAT", type: "Agent" },
    { name: "Markus Delrow | FBI HRT", type: "Agent" },
    { name: "Michael Syfers | FBI Sniper", type: "Agent" },
    { name: "Special Agent Ava | FBI", type: "Agent" },
    { name: "Commander Frank 'Wet Sox' Baroud | SEAL Frogman", type: "Agent" },
    { name: "Lieutenant Rex Krikey | SEAL Frogman", type: "Agent" },
    { name: "'Two Times' McCoy | USAF TACP", type: "Agent" },
    { name: "Buckshot | NSWC SEAL", type: "Agent" },
    { name: "Cmdr. Davida 'Goggles' Fernandez | SEAL Frogman", type: "Agent" },

    // ===== PATCHES =====
    { name: "Patch | Metal The Champion", type: "Patch" },
    { name: "Patch | Metal The Global Elite", type: "Patch" },
    { name: "Patch | Metal Supreme Master First Class", type: "Patch" },

    // ===== MUSIC KITS =====
    { name: "Music Kit | Austin Wintory, Desert Fire", type: "Music Kit" },
    { name: "Music Kit | Darude, Sandstorm", type: "Music Kit" },
    { name: "Music Kit | Feed Me, High Noon", type: "Music Kit" },

    // ===== TOOLS =====
    { name: "Name Tag", type: "Tool" },
    { name: "StatTrak™ Swap Tool", type: "Tool" },
    { name: "Storage Unit", type: "Tool" },

    // ===== COLLECTIBLES =====
    { name: "Souvenir Package", type: "Collectible" },
    { name: "Souvenir Package (Katowice 2014)", type: "Collectible" },
    { name: "Souvenir Package (Cologne 2014)", type: "Collectible" },
    { name: "Souvenir Package (DreamHack 2014)", type: "Collectible" },
    { name: "Pin | Guardian Elite", type: "Collectible" },
    { name: "Pin | Howl", type: "Collectible" },
];
